// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmhxzemqhmsvpivpgmdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaHh6ZW1xaG1zdnBpdnBnbWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzk3NjQsImV4cCI6MjA2MDIxNTc2NH0.TfktCXJQdiTAgY0dLWMggtw4_ZoeshOmYtozUy737Wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);